No se encontraron los dropdowns: Page.wait_for_selector: Timeout 60000ms exceeded.
Call log:
  - waiting for locator("#filialCombobox") to be visible
    121 × locator resolved to hidden <input required="" name="filial" kendo-combo-box="" id="filialCombobox" k-auto-bind="false" data-role="combobox" aria-disabled="false" k-clear-button="false" k-data-text-field="'value'" k-data-value-field="'code'" k-options="kOptions.filial" data-ng-model="filialIdBind" k-on-change="onChangeFilial()" k-data-source="dataSourceFilial" data-required-msg="Debe seleccionar una  filial" class="form-combobox ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required"/>


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
<div class="k-list-scroller" unselectable="on" style="height: auto;"><ul unselectable="on" class="k-list k-reset" tabindex="-1" aria-hidden="true" id="filialCombobox_listbox" aria-live="off" data-role="staticlist" role="listbox"><li tabindex="-1" role="option" unselectable="on" class="k-item ng-scope k-state-focused k-state-selected" aria-selected="true" data-offset-index="0" id="b7ceaaa6-fb09-4ff0-ab71-651fafe9171b">BANISTMO S.A.</li></ul></div>
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
File "C:\Users\katejada\Desktop\Codigos y .Exe\ACH\cross3.py", line 54, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 719, in run_until_complete       
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\katejada\Desktop\Codigos y .Exe\ACH\cross3.py", line 31, in main
    await page.wait_for_selector('input[type="email"]')
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\async_api\_generated.py", line 8181, in wait_for_selector
    await self._impl_obj.wait_for_selector(
        selector=selector, timeout=timeout, state=state, strict=strict
    )
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_page.py", line 423, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_frame.py", line 369, in wait_for_selector
    await self._channel.send(
        "waitForSelector", self._timeout, locals_to_params(locals())
    )
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_connection.py", line 69, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\katejada\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_connection.py", line 558, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("input[type=\"email\"]") to be visible


??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
carpeta_salida = r"\\ntappama01-c01\Herramienta Usuario Final en Ejecucion\REVISION XPRESS"
if not os.path.exists(carpeta_salida):
    os.makedirs(carpeta_salida, exist_ok=True)
ruta_pdf = os.path.join(carpeta_salida, f"{pdf_name}.pdf")



\\ntappama01-c01\Herramienta Usuario Final en Ejecucion\REVISION XPRESS

carpeta_salida = r"\\ntappama01-c01\Herramienta Usuario Final en Ejecucion\REVISION XPRESS"
if not os.path.exists(carpeta_salida):
    # Opcional: crear carpeta, o lanzar error si no existe o sin permiso
    os.makedirs(carpeta_salida, exist_ok=True)
ruta_pdf = os.path.join(carpeta_salida, f"{pdf_name}.pdf")



Referencia hard.xlsx ignorada por no tener suficientes columnas
Traceback (most recent call last):
  File "C:\Users\katejada\Desktop\Codigos y .Exe\ACH\cross3.py", line 150, in <module>
    raise ValueError("No se pudieron procesar archivos de referencia válidos.")
ValueError: No se pudieron procesar archivos de referencia válidos.


error 2 
Error procesando referencia hard.xlsx: Unencrypted document
Traceback (most recent call last):
  File "C:\Users\katejada\Desktop\Codigos y .Exe\ACH\cross3.py", line 195, in <module>
    raise ValueError("No se pudieron procesar archivos de referencia válidos.")
ValueError: No se pudieron procesar archivos de referencia válidos.
